---
- name: Build brotli
  ansible.builtin.shell: |
    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_CXX_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_INSTALL_PREFIX=./installed ..
    cmake --build . --config Release -j 2 --target brotlienc
  args:
   chdir: /root/ngx_brotli/deps/brotli/out

- name: Create RPM Pkg
  ansible.builtin.shell: rpmbuild -ba nginx.spec -D 'debug_package %{nil}'
  args:
   chdir: /root/rpmbuild/SPECS

- name: Add Text
  ansible.builtin.shell: |
    echo "[otus]
    name=otus-linux
    baseurl=http://localhost/repo
    gpgcheck=0 
    enabled=1" | tee -a /etc/yum.repos.d/otus.repo
    yum repolist enabled
...
